[package]
name = "fdg-2d-macroquad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdg-sim = { path = "../fdg-sim" }
macroquad = "0.3.15"
