[package]
name = "fdg-macroquad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = "0.9"
fdg-sim = { path = "../fdg-sim", features = ["json"] }
macroquad = "0.3"

[dev-dependencies]
pretty_env_logger = "0.4"
