[package]
name = "fdg-macroquad"
version = "0.2.1"
edition = "2021"
authors = ["Grant Handy <grantshandy@gmail.com>"]
license = "GPL-3.0"
description = "The macroquad based visualizer for fdg"
repository = "https://github.com/skylinecc/fdg/"
documentation = "https://docs.rs/fdg_macroquad/"
keywords = ["graph", "force", "macroquad"]
categories = ["visualization"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = "0.9"
#fdg-sim = { path = "../fdg-sim", features = ["json"] }
fdg-sim = { version = "0.2", features = ["json"] }
macroquad = "0.3"
serde = { version = "1.0.140", features = ["derive"] }
jsonxf = "1.1.1"
serde_json = "1.0"

[dev-dependencies]
pretty_env_logger = "0.4"
