[package]
name = "fdg-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# simulation
glam = "0.20"
log = "0.4"
rand = "0.8"
petgraph = "0.6"
