[package]
name = "fdg-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20"
log = "0.4"
rand = "0.8"
petgraph = "0.6"
regex = "1.5"
serde_json = { version = "1.0", optional = true }

[features]
json = ["serde_json"]